version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_staycation
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_staycation
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=db
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: db_staycation_app
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db
